name: CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ghcr.io/colashn65/december .
      - run: docker push ghcr.io/colashn65/december
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: send default messgae
        if: success()
        uses: appleboy/telegram-action@master
        with:
          message: "Сделано успешно"
          to: 1680135436
          token: 6858811804:AAEg1CXKjqsilxqyd3-Eq6GAk7UkedYkblU
      - name: send default message
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          message: "Сделано неуспешно"
          to: 1680135436
          token: 6858811804:AAEg1CXKjqsilxqyd3-Eq6GAk7UkedYkblU
        
